name: syzygy
description: Syzygy Flame game
version: 0.0.0
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ^3.13.0

dependencies:
  flame: ^1.12.0
  flutter:
    sdk: flutter

flutter:
  assets:
    - assets/images/